// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// DataProvider is an autogenerated mock type for the DataProvider type
type DataProvider struct {
	mock.Mock
}

// GetData provides a mock function with given fields: ctx, inn
func (_m *DataProvider) GetData(ctx context.Context, inn string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, inn)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, inn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
