// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	io "io"

	models "github.com/ivanovaleksey/rusprofile/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: _a0
func (_m *Parser) Parse(_a0 io.Reader) (models.CompanyInfo, error) {
	ret := _m.Called(_a0)

	var r0 models.CompanyInfo
	if rf, ok := ret.Get(0).(func(io.Reader) models.CompanyInfo); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.CompanyInfo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
